### ISSUE TITLE
Inspector - Backup Space Check not looking at correct day

### ISSUE THREAD

**Issue by PeterJenner1992** [SQLUndercover/UndercoverToolbox#187]
Backup space report is looking at backups that take on the current day rather than the next day.

This means with backups scheduled after midnight the space reports are not reporting the correct backup space requirements for the next 24 hours

**Comment by Adedba** [comment]
Thanks @PeterJenner1992 , looks like I introduced this one in the latest release as I changed the logic due to an issue where it was looking at the next day. 

I will get that logic back in there with a hotfix but make it configurable using DATEADD because for some users depending on what time of day they run their reports and depending on when they run their large backups may actually want to see what is going to happen today. 

Makes perfect sense to be able to see the next 24 hours especially if backup space is running low. 

I will add a new setting to the settings table to control the behaviour but default to to a 1: DATENAME(WEEKDAY,DATEADD(DAY,1,GETDATE()))  

the opposite setting will be a 0 
DATENAME(WEEKDAY,DATEADD(DAY,0,GETDATE()))  

this way we cover both angles.

Thanks again for reporting.

**Comment by Adedba** [comment]
Whilst making the changes I noticed that there is missing AND clause in BackupSpaceInsert this additional clause stops backup sizes for the current day being inserting into the table Inspector.BackupSpace. Without the clause (the current behaviour) you will get last weeks' current day so for today that would be Wednesday of last weeks backup total plus whatever has been taken today up to the collection time therefore the estimate is not correct.

Regarding the issue raised I have included the above plus changed a where clause in Inspector.BackupSpaceReport and added a new setting to Inspector.Settings (BackupSpaceWeekdayOffset), supported values are 0 and 1.

1 - Offset the current day by one day i.e DATENAME(WEEKDAY,DATEADD(DAY,1,GETDATE())) - return the day of the week for tomorrow and then get the data for that day of the week from the BackupSpace table.

0 - No offset - use the current days' weekday i.e DATENAME(WEEKDAY,DATEADD(DAY,1,GETDATE()))
